const genres = {
  Action: "/genre/action",
  "Adult Cast": "/genre/adult-cast",
  Adventure: "/genre/adventure",
  Anthropomorphic: "/genre/anthropomorphic",
  "Avant Garde": "/genre/avant-garde",
  "Award Winning": "/genre/award-winning",
  Cars: "/genre/cars",
  CGDCT: "/genre/cgdct",
  Childcare: "/genre/childcare",
  "Combat Sports": "/genre/combat-sports",
  Comedy: "/genre/comedy",
  Comic: "/genre/comic",
  Crime: "/genre/crime",
  Cultivation: "/genre/cultivation",
  Delinquents: "/genre/delinquents",
  Dementia: "/genre/dementia",
  Demons: "/genre/demons",
  Detective: "/genre/detective",
  Drama: "/genre/drama",
  Dub: "/genre/dub",
  Ecchi: "/genre/ecchi",
  Educational: "/genre/educational",
  Erotica: "/genre/erotica",
  Family: "/genre/family",
  Fantasy: "/genre/fantasy",
  "Gag Humor": "/genre/gag-humor",
  Game: "/genre/game",
  "Gender Bender": "/genre/gender-bender",
  Gore: "/genre/gore",
  Gourmet: "/genre/gourmet",
  Harem: "/genre/harem",
  Hentai: "/genre/hentai",
  "High Stakes Game": "/genre/high-stakes-game",
  Historical: "/genre/historical",
  Horror: "/genre/horror",
  "Idols (Female)": "/genre/idols-female",
  Isekai: "/genre/isekai",
  Iyashikei: "/genre/iyashikei",
  Josei: "/genre/josei",
  Kids: "/genre/kids",
  "Love Polygon": "/genre/love-polygon",
  Magic: "/genre/magic",
  "Magical Sex Shift": "/genre/magical-sex-shift",
  "Mahou Shoujo": "/genre/mahou-shoujo",
  "Martial Arts": "/genre/martial-arts",
  Mecha: "/genre/mecha",
  Medical: "/genre/medical",
  Military: "/genre/military",
  Music: "/genre/music",
  Mystery: "/genre/mystery",
  Mythology: "/genre/mythology",
  "Organized Crime": "/genre/organized-crime",
  "Otaku Culture": "/genre/otaku-culture",
  Parody: "/genre/parody",
  "Performing Arts": "/genre/performing-arts",
  Pets: "/genre/pets",
  Police: "/genre/police",
  Psychological: "/genre/psychological",
  Racing: "/genre/racing",
  Reincarnation: "/genre/reincarnation",
  "Reverse Harem": "/genre/reverse-harem",
  Romance: "/genre/romance",
  "Romantic Subtext": "/genre/romantic-subtext",
  Samurai: "/genre/samurai",
  School: "/genre/school",
  "Sci-Fi": "/genre/sci-fi",
  Seinen: "/genre/seinen",
  Shoujo: "/genre/shoujo",
  "Shoujo Ai": "/genre/shoujo-ai",
  Shounen: "/genre/shounen",
  Showbiz: "/genre/showbiz",
  "Slice of Life": "/genre/slice-of-life",
  Space: "/genre/space",
  Sports: "/genre/sports",
  "Strategy Game": "/genre/strategy-game",
  "Strong Male Lead": "/genre/strong-male-lead",
  "Super Power": "/genre/super-power",
  Supernatural: "/genre/supernatural",
  Survival: "/genre/survival",
  Suspense: "/genre/suspense",
  System: "/genre/system",
  "Team Sports": "/genre/team-sports",
  Thriller: "/genre/thriller",
  "Time Travel": "/genre/time-travel",
  "Urban Fantasy": "/genre/urban-fantasy",
  Vampire: "/genre/vampire",
  "Video Game": "/genre/video-game",
  Villain: "/genre/villain",
  "Visual Arts": "/genre/visual-arts",
  "Work Life": "/genre/work-life",
  Workplace: "/genre/workplace",
};

export async function getGenreList() {
  return Object.keys(genres);
}

export async function getGenreLink(name) {
  return genres[name];
}
